version: "3.9"
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
  db:
    container_name: postgres-db
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always




